---
title: "Probability"
author: "fasehab"
execute:
  echo: false
---

```{r}
#| message: false
library(tidyverse)
```

```{r}
#| cache: true
throw_dice <- function(n, weights = rep(1/6, 6)) {
  die1 <- sample(1:6, size = n, replace = TRUE, prob = weights)
  die2 <- sample(1:6, size = n, replace = TRUE, prob = weights)
  die1 + die2
}
```

```{r}
set.seed(10)

weights <- c(rep(0.75 / 5, 5), 0.25)

expand_grid(n = c(10, 20, 50, 100, 1000)) |>
  mutate(sum = map(n, ~ throw_dice(.x, weights = weights))) |>
  unnest(sum) |>
  ggplot(aes(x = sum)) +
  geom_histogram(binwidth = 1, color = "black", fill = "lightblue") +
  scale_x_continuous(breaks = 2:12) +
  facet_wrap(~ n, scales = "free_y") +
  labs(x = "Sum of two dice", y = "Count")
```

```{r}
#| cache: true
fair <- c(1/6, 1/6, 1/6, 1/6, 1/6, 1/6)
loaded <- c(rep(0.75 / 5, 5), 0.25)

log_lr <- function(rolls) {
  log(loaded[rolls]) - log(fair[rolls])
}
```

```{r}
set.seed(10)

stopping_times <- map_int(1:1000, function(i) {
  rolls <- sample(1:6, 10000, replace = TRUE, prob = c(0.14, 0.14, 0.14, 0.14, 0.14, 0.30))
  log_odds <- cumsum(log_lr(rolls))
  posterior <- 1 / (1 + exp(-log_odds))
  which(posterior >= 0.95)[1]
})

tibble(stopping_time = stopping_times) |>
  ggplot(aes(x = stopping_time)) +
  geom_histogram(binwidth = 5, color = "black", fill = "lightblue") +
  labs(x = "Roll when posterior first reaches 0.95", y = "Count")
```

